### ISSUE TITLE
Troubles installing on linux

### ISSUE THREAD

**Issue by chpill** [cognitect-labs/test-runner#1] opened 2018-02-18 19:55 UTC
I wanted to try out this library, so I run the following command on my linux box:

```
clojure -Sdeps '{:deps {com.cognitect/test-runner {:git/url "git@github.com:cognitect-labs/test-runner" :sha "dc5c899ff0dbb2c3651f6c90d12b594e45ae6452"}}}'
```

I got the following error:

```
Error building classpath. git@github.com:cognitect-labs/test-runner: java.lang.NoClassDefFoundError: com/jcraft/jzlib/ZStream
org.eclipse.jgit.api.errors.TransportException: git@github.com:cognitect-labs/test-runner: java.lang.NoClassDefFoundError: com/jcraft/jzlib/ZStream
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:248)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:89)
	at clojure.tools.gitlibs.impl$call_with_auth.invokeStatic(impl.clj:49)
	at clojure.tools.gitlibs.impl$call_with_auth.invoke(impl.clj:41)
	at clojure.tools.gitlibs.impl$git_clone_bare.invokeStatic(impl.clj:71)
	at clojure.tools.gitlibs.impl$git_clone_bare.invoke(impl.clj:68)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invokeStatic(impl.clj:106)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invoke(impl.clj:100)
	at clojure.tools.gitlibs$resolve.invokeStatic(gitlibs.clj:27)
	at clojure.tools.gitlibs$resolve.invoke(gitlibs.clj:23)
	at clojure.tools.gitlibs$procure.invokeStatic(gitlibs.clj:41)
	at clojure.tools.gitlibs$procure.invoke(gitlibs.clj:35)
	at clojure.tools.deps.alpha.extensions.git$eval958$fn__960.invoke(git.clj:35)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:153)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:137)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:191)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:182)
	at clojure.tools.deps.alpha.script.make_classpath$run.invokeStatic(make_classpath.clj:56)
	at clojure.tools.deps.alpha.script.make_classpath$run.invoke(make_classpath.clj:44)
	at clojure.tools.deps.alpha.script.make_classpath$_main.invokeStatic(make_classpath.clj:98)
	at clojure.tools.deps.alpha.script.make_classpath$_main.doInvoke(make_classpath.clj:73)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:cognitect-labs/test-runner: java.lang.NoClassDefFoundError: com/jcraft/jzlib/ZStream
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:172)
	at clojure.tools.gitlibs.impl.proxy$org.eclipse.jgit.transport.JschConfigSessionFactory$ff19274a.getSession(Unknown Source)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1269)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:237)
	... 33 more
Caused by: com.jcraft.jsch.JSchException: java.lang.NoClassDefFoundError: com/jcraft/jzlib/ZStream
	at com.jcraft.jsch.Session.initDeflater(Session.java:2241)
	at com.jcraft.jsch.Session.read(Session.java:1048)
	at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:198)
	at com.jcraft.jsch.Session.connect(Session.java:470)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:126)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: com/jcraft/jzlib/ZStream
	at com.jcraft.jsch.jcraft.Compression.<init>(Compression.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.jcraft.jsch.Session.initDeflater(Session.java:2234)
	... 45 more
Caused by: java.lang.ClassNotFoundException: com.jcraft.jzlib.ZStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
```

Other dependencies were installed correctly, I do not really know if the error is in tools.deps or elsewhere.

Anyone else having trouble installing this library? Any idea what might be wrong here?

**Comment by mathpunk** [comment] 2018-02-18 21:28
I tried reproducing this. On my Linux box, the same command yielded 

    Cloning: git@github.com:cognitect-labs/test-runner
    Error building classpath. connector is not available: 
    com.jcraft.jsch.agentproxy.AgentProxyException: connector is not available: 
	    at com.jcraft.jsch.agentproxy.ConnectorFactory.createConnector(ConnectorFactory.java:120)
	    at clojure.tools.gitlibs.impl$fn__883.invokeStatic(impl.clj:30)
	    at clojure.tools.gitlibs.impl$fn__883.invoke(impl.clj:28)
	    at clojure.lang.Delay.deref(Delay.java:42)
	    at clojure.core$deref.invokeStatic(core.clj:2312)
	    at clojure.core$deref.invoke(core.clj:2298)
	    at clojure.tools.gitlibs.impl$call_with_auth.invokeStatic(impl.clj:49)
	    at clojure.tools.gitlibs.impl$call_with_auth.invoke(impl.clj:41)
	    at clojure.tools.gitlibs.impl$git_clone_bare.invokeStatic(impl.clj:71)
	    at clojure.tools.gitlibs.impl$git_clone_bare.invoke(impl.clj:68)
	    at clojure.tools.gitlibs.impl$ensure_git_dir.invokeStatic(impl.clj:106)
	    at clojure.tools.gitlibs.impl$ensure_git_dir.invoke(impl.clj:100)
	    at clojure.tools.gitlibs$resolve.invokeStatic(gitlibs.clj:27)
	    at clojure.tools.gitlibs$resolve.invoke(gitlibs.clj:23)
	    at clojure.tools.gitlibs$procure.invokeStatic(gitlibs.clj:41)
	    at clojure.tools.gitlibs$procure.invoke(gitlibs.clj:35)
	    at clojure.tools.deps.alpha.extensions.git$eval941$fn__943.invoke(git.clj:35)
	    at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	    at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:145)
	    at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:129)
	    at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:183)
	    at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:174)
	    at clojure.tools.deps.alpha.script.make_classpath$run.invokeStatic(make_classpath.clj:42)
	    at clojure.tools.deps.alpha.script.make_classpath$run.invoke(make_classpath.clj:36)
	    at clojure.tools.deps.alpha.script.make_classpath$_main.invokeStatic(make_classpath.clj:72)
	    at clojure.tools.deps.alpha.script.make_classpath$_main.doInvoke(make_classpath.clj:51)
	    at clojure.lang.RestFn.applyTo(RestFn.java:137)
	    at clojure.lang.Var.applyTo(Var.java:702)
	    at clojure.core$apply.invokeStatic(core.clj:657)
	    at clojure.main$main_opt.invokeStatic(main.clj:317)
	    at clojure.main$main_opt.invoke(main.clj:313)
	    at clojure.main$main.invokeStatic(main.clj:424)
	    at clojure.main$main.doInvoke(main.clj:387)
	    at clojure.lang.RestFn.applyTo(RestFn.java:137)
	    at clojure.lang.Var.applyTo(Var.java:702)
      at clojure.main.main(main.java:37)

Then I tried to use [these directions](https://github.com/cognitect-labs/test-runner#usage), both with the sha hash there and with the hash @chpill tried. Invoking `clj -Atest` yielded `java.io.FileNotFoundException: -Atest (No such file or directory)`.

**Comment by chpill** [comment] 2018-02-19 08:09
I tried the install on my machine at work (also a linux) and it worked this time, with both of the shas `5fb4fc46ad0bf2e0ce45eba5b9117a2e89166479` and `dc5c899ff0dbb2c3651f6c90d12b594e45ae6452`

Very strange...

**Comment by levand** [comment] 2018-02-19 20:37
I'll try to replicate this in a VM when I get some time. Before I do, can I ask what distro/version, and what Java version you were using when you saw this @chpill @mathpunk ?

**Comment by mathpunk** [comment] 2018-02-19 23:34
Arch Linux: 
4.15.2-2-ARCH x86_64 GNU/Linux

Java:
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by chpill** [comment] 2018-02-22 15:34
Mine was a debian 4.13 x86_64

Not sure about the java version, I will try to check when I can put my hands on the machine again

**Comment by seancorfield** [comment] 2018-02-22 22:52
I think the `:git/url` needs to be `"https://github.com/cognitect-labs/test-runner"` -- the `git@github` version needs auth access to this repo?

**Comment by mathpunk** [comment] 2018-02-23 18:32
I tried changing the URL: `clojure -Sdeps '{:deps {com.cognitect/test-runner {:git/url "https://github.com:cognitect-labs/test-runner" :sha "5fb4fc46ad0bf2e0ce45eba5b9117a2e89166479"}}}'`

yields 

    Error building classpath. Exception caught during execution of fetch command
    org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
    	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:254)
    	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand...

and more, but this line jumped out at me 'cause yeah, that URI wouldn't be supported---

`Caused by: org.eclipse.jgit.errors.NotSupportedException: URI not supported: https:///github.com:cognitect-labs/test-runner` (note the triple slash, which I don't think is in the command I typed)

**Comment by seancorfield** [comment] 2018-02-23 18:37
You still have a `:` where you should have `/`.

**Comment by mathpunk** [comment] 2018-02-23 18:46
ha, whoops. And, there's a repl.

**Comment by SevereOverfl0w** [comment] 2018-03-24 10:01
I think this is the same as #8, to some degree.

**Comment by ashnur** [comment] 2019-12-02 07:59
I got the `com.jcraft.jsch.agentproxy.AgentProxyException: connector is not available: ` error on Arch Linux, after changing the path to `https:...` as @seancorfield suggests, everything worked fine.

**Comment by puredanger** [comment] 2020-05-19 17:20
Closing, I think just using https protocol here is all that's needed. Please file a fresh issue if you encounter an error with that.

**Closed as completed by puredanger** 2020-05-19 17:20 UTC

**Comment by dcostaras** [comment] 2020-08-07 14:00
For posterity: I ran into this error recently and Alex Miller quickly diagnosed it. It is also, currently, triggered by having `compression yes` in your ssh config. Alex will add a fix to the next (as of this reply) version of `clj`

**Comment by puredanger** [comment] 2020-08-07 14:22
Logged at https://clojure.atlassian.net/browse/TDEPS-160 and will be fixed in next prerelease version of clj
